-- Основная таблица автомобилей
CREATE TABLE IF NOT EXISTS cars (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_name        VARCHAR(64) NOT NULL,
    city            VARCHAR(64) NOT NULL,
    car_class       VARCHAR(16) NOT NULL,
    price           NUMERIC(19, 2) NOT NULL,
    car_status      VARCHAR(16) NOT NULL,
    created_at      TIMESTAMPTZ DEFAULT current_timestamp,
    updated_at      TIMESTAMPTZ DEFAULT current_timestamp
);